- name: Configure Apache inside Docker container
  hosts: apache
  tasks:
    - name: Copy custom index.html
      copy:
        content: |
          <html>
          <body>
            <div style="background-color: #333; padding: 10px;">
              <a href="#home" style="color: white; text-decoration: none; margin-right: 15px;">Home</a>
              <a href="#about" style="color: white; text-decoration: none; margin-right: 15px;">About</a>
              <a href="#contact" style="color: white; text-decoration: none;">Contact</a>
              <form action="/action_page.php" style="display: inline-block; float: right;">
                <input type="text" placeholder="Search.." name="search" style="padding: 5px;">
                <button type="submit" style="padding: 5px;">Submit</button>
              </form>
            </div>

            <h1>Hello I am Yan Yan :)</h1>
            <h2 style="font-family: 'Courier New', Courier, monospace;">The previous 'It works!' has been changed to this!</h2>
            <h3 style="color: blue;">This webpage has been changed by running Ansible Playbooks from Jenkins.</h3>
            
            <img src="https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg" alt="Dog Image" width="500" height="300">
            <br><br>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/gGcubGOqDHE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </body>
          </html>
        dest: /usr/local/apache2/htdocs/index.html
