- hosts: linux
  become: true
  tasks:
    - name: Add Google Linux signing key
      shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - iproute2
        - wget
        - python3

    - name: Configure IP address on eth1
      command: ip addr add 192.168.1.100/24 dev eth1
      ignore_errors: yes

    - name: Add route to Apache server subnet
      command: ip route add 192.168.2.0/24 dev eth1
      ignore_errors: yes
      
